name: Blog

env:
  AWS_REGION: us-east-1

on:

  workflow_dispatch:
    paths:
      - "blog/**"
    
  push:
    paths:
      - "blog/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:

    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # - name: Install AWS CLI
    #   run:  |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     sudo ./aws/install

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    # - name: Setup Hugo
    #   run: |
    #     wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
    #     sudo dpkg -i hugo*.deb

    # - name: Hugo Version?
    #   run: hugo version
    
    # - name: Run Hugo
    #   run: hugo

    # - name: Build with with hugo
    #   env:
    #     HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
    #     TZ: America/Los_Angeles
    #   run: hugo --gc --logLevel info

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      
    - name: Deploy with Hugo
      run: hugo deploy [--target=cloud-resume-blog]
