name: Blog

env:
  AWS_REGION: us-east-1

on:

  workflow_dispatch:
    paths:
      - "blog/**"
    
  push:
    paths:
      - "blog/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Clone
      uses: actions/checkout@v4

    # - name: Install AWS CLI
    #   run:  |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     sudo ./aws/install

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'

    - name: Hugo Version?
      run: hugo version

    - name: Build with with hugo
      run: hugo
      
    - name: Deploy with Hugo
      run: hugo deploy [--target=cloud-resume-blog]
