name: Blog

env:
  AWS_REGION: us-east-1

on:
  workflow_dispatch:
    paths:
      - "blog/**"
    
  push:
    paths:
      - "blog/**"

defaults:
  run:
    working-directory: ./blog
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HUGO_VERSION: 0.128.2
    steps:

    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        sudo dpkg -i hugo*.deb
      
    - name: Display current directory
      run: echo ${GITHUB_WORKSPACE}

    - name: lsl
      run: ls -l

    - name: Change directory
      run: cd  ${{ inputs.working_directory }}

    - name: Build Hugo
      run: hugo --gc --minify 

    - name: Deploy with Hugo
      run: |
        hugo deploy [--target=deploy-blog]