name: Github Actions Test

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

on:
  workflow_dispatch:
    paths:
    - "resume/**"

  push:
    paths:
      - "resume/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.CLOUD_RESUME_AWS_ACCOUNT_ID }}:role/cloud-resume-github-actions
        role-session-name: github-actions-test-role-sesssion
        aws-region: ${{ env.AWS_REGION }}

    - name: Get Caller Identity
      run: |
          aws sts get-caller-identity
