name: cd

env:
  AWS_REGION: us-east-1

on:
  push:
    paths:
      - "assests/**"
      - "content/**"
      - "extra/**"
      - "layouts/**"
      - "static/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Clone
      uses: actions/checkout@v2


    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: init for theme
      run: git init

    - name: Get blowfish
      run: git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish 

    - name: Build with with hugo
      run: hugo --minify

    - name: Deploy with Hugo
      run: hugo deploy [--target=cloud-resume-blog]
