name: cd

env:
  AWS_REGION: us-east-1

on:
  push:
    paths:
      - "assests/**"
      - "content/**"
      - "extra/**"
      - "layouts/**"
      - "static/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Clone
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run:  |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    #Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Build with with hugo
      uses: hugo

    - name: Deploy with Hugo
      uses: hugo deploy [--target=cloud-resume-blog]
