name: Resume S3 Bucket Sync

env:
  AWS_REGION: us-east-1

on:

  workflow_dispatch:
    paths:
    - "resume/**"

  push:
    paths:
      - "resume/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.CLOUD_RESUME_AWS_ACCOUNT_ID }}:role/cloud-resume-github-actions
        role-session-name: github-actions-test-role-sesssion
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./resume s3://${{ secrets.RESUME_BUCKET }} --delete

    - name: Invalidate clodufront distribution
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.RESUME_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
